### ISSUE TITLE
Representación de un Usuario

### ISSUE THREAD

**Issue by Xileon310** [gomares/Proyecto_IV#10]
Como programador imagino que un usuario debe estar registrado antes de valorar un manga o antes de que se le recomiende un manga (puesto que debe tener unas preferencias ya establecidas).

Estimo que se debe crear una representación básica de un Usuario, para ello se creará una clase Usuario.

Avanza #3

**Comment by JJ** [comment]
Si el registro sirve a la lógica de negocio, úsalo. Si no, no.

**Comment by JJ** [comment]
No hay ni un commit en este issue que siga las buenas prácticas. Y algunos que evidencian malas prácticas como referirse a dos issues que no tienen nada que ver.

**Comment by JJ** [comment]
> Como programador imagino que un usuario debe estar registrado antes de valorar un manga o antes de que se le recomiende un manga (puesto que debe tener unas preferencias ya establecidas).
> 

No está justificado.

> Estimo que se debe crear una representación básica de un Usuario, para ello se creará una clase Usuario.

No puede haber planteamiento de un problema menos informativo que esto.
> 
> Avanza #3

Ni esto.

Apreciaría que realmente intentárais entender qué es un issue, qué papel tiene dentro del desarrollo de un proyecto y para qué sirve en el mismo, en vez de simplemente rellenar cosas para cubrir el expediente.
