### ISSUE TITLE
Representación de un manga

### ISSUE THREAD

**Issue by Xileon310** [gomares/Proyecto_IV#8]
Para poder realizar una recomendación de mangas como se muestra en #3 primero se ha de definir como entidad la clase Manga, pues estará relacionada directamente con la lógica de negocio y será la representación de la información más básica con la que trabajará nuestra aplicación. 

Se debe disponer de una clase que tenga atributos que identifiquen de forma unívoca un manga. También tendrá los métodos correspondientes para obtener dichos datos además de una validación para cada atributo que lo requiera.

Avanza #3

**Comment by JJ** [comment]
Un issue es un problema. Y los commits se deben referir a un issue. No sucede ni lo uno ni lo otro aquí. Por supuesto, tiene que estar basado en una HU.

**Comment by JJ** [comment]
> Un issue es un problema. Y los commits se deben referir a un issue. No sucede ni lo uno ni lo otro aquí. Por supuesto, tiene que estar basado en una HU.

Ningún caso a esto.
